"""Vectorize the public ScaleSuite logo PNG into SVG paths (mark silhouette + wordmark by colour)."""
from PIL import Image
import numpy as np, potrace

SRC = 'ScaleSuiteLogo.png'
UP = 6  # upscale before tracing for smoother curves
im = Image.open(SRC).convert('RGBA')
W, H = im.size
big = im.resize((W * UP, H * UP), Image.LANCZOS)
a = np.asarray(big).astype(np.float32)
R, G, B, A = a[..., 0], a[..., 1], a[..., 2], a[..., 3]
MARK_X = 118 * UP  # mark occupies x < 118 in source

def trace(mask):
    bm = potrace.Bitmap(~mask)
    path = bm.trace(turdsize=20, turnpolicy=potrace.POTRACE_TURNPOLICY_MINORITY, alphamax=1.0, opticurve=True, opttolerance=0.2)
    d = []
    for curve in path:
        s = curve.start_point
        d.append(f"M{s.x/UP:.2f},{s.y/UP:.2f}")
        for seg in curve.segments:
            if seg.is_corner:
                d.append(f"L{seg.c.x/UP:.2f},{seg.c.y/UP:.2f}L{seg.end_point.x/UP:.2f},{seg.end_point.y/UP:.2f}")
            else:
                d.append(f"C{seg.c1.x/UP:.2f},{seg.c1.y/UP:.2f} {seg.c2.x/UP:.2f},{seg.c2.y/UP:.2f} {seg.end_point.x/UP:.2f},{seg.end_point.y/UP:.2f}")
        d.append('Z')
    return ''.join(d)

xs = np.arange(a.shape[1])[None, :]
alpha = A > 128
mark = alpha & (xs < MARK_X)
word = alpha & (xs >= MARK_X)
# dark vs turquoise: turquoise has high G relative to R
turq = word & (G - R > 60)
dark = word & ~turq

shade = mark & (G < 150) & (A > 200)
paths = {'mark': trace(mark), 'shade': trace(shade), 'scale': trace(dark), 'suite': trace(turq)}
for k, v in paths.items():
    open(f'{k}.path.txt', 'w').write(v)
    print(k, len(v))

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W*2}" height="{H*2}">
<defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
<stop offset="0" stop-color="#1FBFA4"/><stop offset=".42" stop-color="#27B6C8"/><stop offset=".62" stop-color="#2FB0DE"/><stop offset="1" stop-color="#1FBCA6"/></linearGradient></defs>
<path d="{paths['mark']}" fill="url(#g)" fill-rule="evenodd"/>
<path d="{paths['shade']}" fill="#16708F" fill-opacity=".55" fill-rule="evenodd"/>
<path d="{paths['scale']}" fill="#1E1E1E" fill-rule="evenodd"/>
<path d="{paths['suite']}" fill="#1FBFA8" fill-rule="evenodd"/>
</svg>'''
open('scalesuite-logo-traced.svg', 'w').write(svg)

# ---- Emit src/logo.js: mark, shade and the wordmark split into letters (by source pixel columns).
import json, re
LETTER_RUNS = [('S', 140, 185), ('c', 191, 232), ('a', 237, 279), ('l', 290, 303), ('e', 312, 358),
               ('S', 366, 411), ('u', 420, 458), ('i', 468, 480), ('t', 485, 512), ('e', 516, 560)]
def subpaths(d):
    return [s for s in re.split(r'(?=M)', d) if s]
def cx(sp):
    xs = [float(v) for v in re.findall(r'(-?\d+\.?\d*),', sp)]
    return (min(xs) + max(xs)) / 2
letters = [{'ch': ch, 'd': '', 'word': 'scale' if i < 5 else 'suite'} for i, (ch, a0, a1) in enumerate(LETTER_RUNS)]
for key in ('scale', 'suite'):
    for sp in subpaths(paths[key]):
        c = cx(sp)
        best = min(range(len(LETTER_RUNS)), key=lambda i: 0 if LETTER_RUNS[i][1] - 2 <= c <= LETTER_RUNS[i][2] + 2 else min(abs(c - LETTER_RUNS[i][1]), abs(c - LETTER_RUNS[i][2])))
        letters[best]['d'] += sp
for i, l in enumerate(letters):
    l['x0'], l['x1'] = LETTER_RUNS[i][1], LETTER_RUNS[i][2]
js = '/* Generated by assets/logo/trace_logo.py from the public ScaleSuite logo (scalesuiteqc.ca/ScaleSuiteLogo.png). */\n'
js += 'window.SS = window.SS || {};\nSS.LOGO = ' + json.dumps({'w': W, 'h': H, 'mark': paths['mark'], 'shade': paths['shade'], 'letters': letters}) + ';\n'
open('../../src/logo.js', 'w').write(js)
print('letters', [(l['ch'], len(l['d'])) for l in letters])
